version: 2.1
jobs:
  # print_owner:
  #   docker:
  #     - image: cimg/base:2020.01
  #   steps:
  #     - run:
  #         name: "echo an env var that is part of our project"
  #         command: |
  #           echo $AWS_ACCESS_KEY_ID
  # learn-checkout:
  #   docker:
  #     - image: cimg/base:2020.01
  #   steps:
  #     - checkout
  #     - run:
  #         name: "cat README.md"
  #         command: |
  #           cat README.md

  run-cloudformation:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID          
      - run: export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - run: export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
      - run:
          name: "Create CloudFormation Stack"
          command: |
            aws cloudformation create-stack --stack-name myfirsttest --template-body file://stack.yml
      
workflows:
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      #- print_owner
      - run-cloudformation