version: 2.1
jobs:
  print_owner:
    docker:
      - image: cimg/base:2020.01
    steps:
      - run:
          name: "echo an env var that is part of our project"
          command: |
            echo $AWS_ACCESS_KEY_ID
workflows:
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - print_owner