version: 2.1
jobs:
  # Cloudformation to create stack
  # run-cloudformation:
  #   docker:
  #     - image: amazon/aws-cli
  #   steps:
  #     - checkout
  #     - run:
  #         name: "Create CloudFormation Stack"
  #         command: |
  #           aws cloudformation create-stack --stack-name myfirsttest --template-body file://stack.yml
  
  # configure infra using ansible
  configure-environment:
    docker:
      - image: python:3.7-alpine3.11
    steps:
    - add_ssh_keys:
          fingerprints:
            - "4f:66:70:dc:47:8d:20:bf:ed:b3:1e:a2:1c:92:9d:bd"
    - checkout
    - run:
        name: "Install Ansible using apk"
        command: |
          apk add ansible
    - run: export ANSIBLE_HOST_KEY_CHECKING=False
    - run:
        name: "Configure Node.js on new ubuntu server"
        command: |
          echo "[defaults]\nhost_key_checking = False" > ~/.ansible.cfg && ansible-playbook main-remote.yml -i inventory

workflows:
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      #- run-cloudformation
      - configure-environment