---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: "yes"

- name: "remove dependencies that are no longer required"
  become: yes
  apt:
    autoremove: yes

# My work following manual tutorial
# - name: "install node.js prerequisets"
#   become: yes
#   apt:
#     name: build-essential
#     state: latest
#     update_cache: yes

# - name: "Copy install script"
#   copy:
#     src: install_nodejs.sh
#     dest: /tmp/install_nodejs.sh

# - name: "Copy index.js"
#   copy:
#     src: index.js
#     dest: ~/index.js

# - name: "Install Node.js via script"
#   become: yes
#   script: install_nodejs.sh
#   args:
#     chdir: /tmp
#     executable: bash

# - name: "Run index.js"
#   command: node ~/index.js
##########################################

## From Udacity solution (worked)
# - name: "install Node.js from repos"
#   become: yes
#   apt:
#     name: ["nodejs", "npm"]
#     state: latest
#     update_cache: yes

# - name: "Copy index test page"
#   copy:
#     src: "index.js"
#     dest: "~/index.js"

# - name: Executing node
#   shell: |
#     node ~/index.js
##########################################
## From Udacity solution (not tested)
- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Creates directory
  file:
    path: ~/web
    state: directory

- name: Copy index test page
  template:
    src: "files/index.js"
    dest: "~/web/index.js"

- name: Executing node
  shell: |
    pm2 start ~/web/index.js -f
